/**
 * Authored `.dnd5e` documents used by the format tests.
 *
 * The `.dnd5e` format is byte-exact: a UTF-8 BOM, CRLF line endings, tab
 * indentation, no trailing newline, and node-specific empty forms (some nodes
 * are self-closing, some are written as an empty pair). These samples are
 * written line-by-line so those bytes are explicit and cannot be normalised
 * away by an editor.
 */

const document = (lines: readonly string[]): string => `\uFEFF${lines.join("\r\n")}`;

/** A minimal level-1 character: every section present, nothing filled in. */
const MINIMAL_LINES: readonly string[] = [
  "<?xml version=\"1.0\" encoding=\"utf-8\"?>",
  "<character version=\"1.0.3\" preview=\"false\">",
  "\t<!-- Aurora - https://www.aurorabuilder.com -->",
  "\t<!-- information -->",
  "\t<information>",
  "\t\t<group>",
  "\t\t</group>",
  "\t\t<generationOption>1</generationOption>",
  "\t</information>",
  "\t<!-- display data -->",
  "\t<display-properties favorite=\"false\">",
  "\t\t<name>tst</name>",
  "\t\t<race>Rock Gnome</race>",
  "\t\t<class>",
  "\t\t</class>",
  "\t\t<archetype>",
  "\t\t</archetype>",
  "\t\t<background>",
  "\t\t</background>",
  "\t\t<level>1</level>",
  "\t\t<portrait>",
  "\t\t\t<companion>",
  "\t\t\t</companion>",
  "\t\t\t<local>C:\\Portraits\\default-portrait.png</local>",
  "\t\t\t<base64><![CDATA[]]></base64>",
  "\t\t</portrait>",
  "\t</display-properties>",
  "\t<!-- build data -->",
  "\t<build>",
  "\t\t<input>",
  "\t\t\t<name>tst</name>",
  "\t\t\t<gender>Male</gender>",
  "\t\t\t<player-name>Player One</player-name>",
  "\t\t\t<experience>0</experience>",
  "\t\t\t<attacks>",
  "\t\t\t\t<description><![CDATA[]]></description>",
  "\t\t\t</attacks>",
  "\t\t\t<backstory><![CDATA[]]></backstory>",
  "\t\t\t<background-trinket>",
  "\t\t\t</background-trinket>",
  "\t\t\t<background-traits>",
  "\t\t\t</background-traits>",
  "\t\t\t<background-ideals>",
  "\t\t\t</background-ideals>",
  "\t\t\t<background-bonds>",
  "\t\t\t</background-bonds>",
  "\t\t\t<background-flaws>",
  "\t\t\t</background-flaws>",
  "\t\t\t<background>",
  "\t\t\t\t<feature name=\"\">",
  "\t\t\t\t\t<description><![CDATA[]]></description>",
  "\t\t\t\t</feature>",
  "\t\t\t</background>",
  "\t\t\t<organization>",
  "\t\t\t\t<name>",
  "\t\t\t\t</name>",
  "\t\t\t\t<symbol>",
  "\t\t\t\t</symbol>",
  "\t\t\t\t<allies><![CDATA[]]></allies>",
  "\t\t\t</organization>",
  "\t\t\t<additional-features><![CDATA[]]></additional-features>",
  "\t\t\t<currency>",
  "\t\t\t\t<copper>0</copper>",
  "\t\t\t\t<silver>0</silver>",
  "\t\t\t\t<electrum>0</electrum>",
  "\t\t\t\t<gold>0</gold>",
  "\t\t\t\t<platinum>0</platinum>",
  "\t\t\t\t<equipment><![CDATA[]]></equipment>",
  "\t\t\t\t<treasure><![CDATA[]]></treasure>",
  "\t\t\t</currency>",
  "\t\t\t<notes>",
  "\t\t\t\t<note column=\"left\">",
  "\t\t\t\t</note>",
  "\t\t\t\t<note column=\"right\">",
  "\t\t\t\t</note>",
  "\t\t\t</notes>",
  "\t\t\t<quest>",
  "\t\t\t</quest>",
  "\t\t</input>",
  "\t\t<appearance>",
  "\t\t\t<portrait>C:\\Portraits\\default-portrait.png</portrait>",
  "\t\t\t<age>",
  "\t\t\t</age>",
  "\t\t\t<height>2'11\"</height>",
  "\t\t\t<weight>35 lb.</weight>",
  "\t\t\t<eyes>",
  "\t\t\t</eyes>",
  "\t\t\t<skin>",
  "\t\t\t</skin>",
  "\t\t\t<hair>",
  "\t\t\t</hair>",
  "\t\t</appearance>",
  "\t\t<abilities available-points=\"15\">",
  "\t\t\t<strength>10</strength>",
  "\t\t\t<dexterity>10</dexterity>",
  "\t\t\t<constitution>10</constitution>",
  "\t\t\t<intelligence>10</intelligence>",
  "\t\t\t<wisdom>10</wisdom>",
  "\t\t\t<charisma>10</charisma>",
  "\t\t</abilities>",
  "\t\t<elements level-count=\"1\" registered-count=\"3\">",
  "\t\t\t<element type=\"Level\" name=\"1\" id=\"ID_LEVEL_1\">",
  "\t\t\t\t<element type=\"Race\" name=\"Race\" requiredLevel=\"1\" checksum=\"1597ef76\" registered=\"ID_RACE_GNOME\">",
  "\t\t\t\t\t<element type=\"Size\" name=\"Small\" id=\"ID_SIZE_SMALL\" />",
  "\t\t\t\t\t<element type=\"Vision\" name=\"Darkvision\" id=\"ID_VISION_DARKVISION\" />",
  "\t\t\t\t\t<element type=\"Racial Trait\" name=\"Gnome Cunning\" id=\"ID_RACIAL_TRAIT_GNOME_CUNNING\" />",
  "\t\t\t\t\t<element type=\"Language\" name=\"Common\" id=\"ID_LANGUAGE_COMMON\" />",
  "\t\t\t\t\t<element type=\"Language\" name=\"Gnomish\" id=\"ID_LANGUAGE_GNOMISH\" />",
  "\t\t\t\t\t<element type=\"Racial Trait\" name=\"Gnome Subrace\" id=\"ID_RACIAL_TRAIT_GNOME_SUBRACE\">",
  "\t\t\t\t\t\t<element type=\"Sub Race\" name=\"Gnome Subrace\" requiredLevel=\"1\" checksum=\"d8fc9aec\" registered=\"ID_SUB_RACE_ROCK_GNOME\">",
  "\t\t\t\t\t\t\t<element type=\"Racial Trait\" name=\"Artificer\u2019s Lore\" id=\"ID_RACIAL_TRAIT_ARTIFICERS_LORE\" />",
  "\t\t\t\t\t\t\t<element type=\"Racial Trait\" name=\"Tinker\" id=\"ID_RACIAL_TRAIT_TINKER\">",
  "\t\t\t\t\t\t\t\t<element type=\"Proficiency\" name=\"Tool Proficiency (Tinker\u2019s tools)\" id=\"ID_PROFICIENCY_TOOL_PROFICIENCY_TINKERS_TOOLS\" />",
  "\t\t\t\t\t\t\t</element>",
  "\t\t\t\t\t\t</element>",
  "\t\t\t\t\t</element>",
  "\t\t\t\t</element>",
  "\t\t\t\t<element type=\"Class\" name=\"Class\" requiredLevel=\"1\" checksum=\"33a7b15b\" registered=\"\" />",
  "\t\t\t\t<element type=\"Background\" name=\"Background\" requiredLevel=\"1\" checksum=\"6a621392\" registered=\"\" />",
  "\t\t\t\t<element type=\"Alignment\" name=\"Alignment\" requiredLevel=\"1\" checksum=\"c9ac49d5\" registered=\"\" />",
  "\t\t\t\t<element type=\"Deity\" name=\"Deity\" requiredLevel=\"1\" checksum=\"989cce4c\" registered=\"\" />",
  "\t\t\t\t<element type=\"Grants\" name=\"Base\" id=\"ID_INTERNAL_GRANTS_CHARACTER_BASE\" />",
  "\t\t\t\t<element type=\"Grants\" name=\"Spellcasting Base\" id=\"ID_INTERNAL_GRANTS_SPELLCASTING_BASE\" />",
  "\t\t\t\t<element type=\"Grants\" name=\"Base Armor Class\" id=\"ID_INTERNAL_GRANTS_ARMOR_CLASS_BASE\" />",
  "\t\t\t\t<element type=\"Grants\" name=\"Dexterity Modifier\" id=\"ID_INTERNAL_GRANTS_ARMOR_CLASS_DEXTERITY_MODIFIER\" />",
  "\t\t\t\t<element type=\"Grants\" name=\"Constitution Modifier\" id=\"ID_INTERNAL_GRANTS_HP_CONSTITUTION_MODIFIER\" />",
  "\t\t\t</element>",
  "\t\t</elements>",
  "\t\t<defenses>",
  "\t\t\t<conditional>",
  "\t\t\t</conditional>",
  "\t\t</defenses>",
  "\t\t<companion name=\"\">",
  "\t\t\t<attributes>",
  "\t\t\t\t<strength>10</strength>",
  "\t\t\t\t<dexterity>10</dexterity>",
  "\t\t\t\t<constitution>10</constitution>",
  "\t\t\t\t<intelligence>10</intelligence>",
  "\t\t\t\t<wisdom>10</wisdom>",
  "\t\t\t\t<charisma>10</charisma>",
  "\t\t\t</attributes>",
  "\t\t\t<saves>",
  "\t\t\t\t<save ability=\"strength\">0</save>",
  "\t\t\t\t<save ability=\"dexterity\">0</save>",
  "\t\t\t\t<save ability=\"constitution\">0</save>",
  "\t\t\t\t<save ability=\"intelligence\">0</save>",
  "\t\t\t\t<save ability=\"wisdom\">0</save>",
  "\t\t\t\t<save ability=\"charisma\">0</save>",
  "\t\t\t</saves>",
  "\t\t\t<skills>",
  "\t\t\t\t<skill name=\"Acrobatics\">0</skill>",
  "\t\t\t\t<skill name=\"Animal Handling\">0</skill>",
  "\t\t\t\t<skill name=\"Arcana\">0</skill>",
  "\t\t\t\t<skill name=\"Athletics\">0</skill>",
  "\t\t\t\t<skill name=\"Deception\">0</skill>",
  "\t\t\t\t<skill name=\"History\">0</skill>",
  "\t\t\t\t<skill name=\"Insight\">0</skill>",
  "\t\t\t\t<skill name=\"Intimidation\">0</skill>",
  "\t\t\t\t<skill name=\"Investigation\">0</skill>",
  "\t\t\t\t<skill name=\"Medicine\">0</skill>",
  "\t\t\t\t<skill name=\"Nature\">0</skill>",
  "\t\t\t\t<skill name=\"Perception\">0</skill>",
  "\t\t\t\t<skill name=\"Performance\">0</skill>",
  "\t\t\t\t<skill name=\"Persuasion\">0</skill>",
  "\t\t\t\t<skill name=\"Religion\">0</skill>",
  "\t\t\t\t<skill name=\"Sleight of Hand\">0</skill>",
  "\t\t\t\t<skill name=\"Stealth\">0</skill>",
  "\t\t\t\t<skill name=\"Survival\">0</skill>",
  "\t\t\t</skills>",
  "\t\t\t<portrait location=\"local\">",
  "\t\t\t</portrait>",
  "\t\t</companion>",
  "\t\t<equipment>",
  "\t\t\t<storage name=\"#1\" />",
  "\t\t\t<storage name=\"#2\" />",
  "\t\t\t<item identifier=\"ddd7c3bd-bc3b-4218-bb6b-0feac5576609\" name=\"Abacus\" id=\"ID_WOTC_PHB_ITEM_ABACUS\">",
  "\t\t\t\t<details card=\"true\">",
  "\t\t\t\t\t<name>",
  "\t\t\t\t\t</name>",
  "\t\t\t\t\t<notes>",
  "\t\t\t\t\t</notes>",
  "\t\t\t\t</details>",
  "\t\t\t</item>",
  "\t\t</equipment>",
  "\t\t<sum element-count=\"17\">",
  "\t\t\t<element type=\"Level\" id=\"ID_LEVEL_1\" />",
  "\t\t\t<element type=\"Grants\" id=\"ID_INTERNAL_GRANTS_CHARACTER_BASE\" />",
  "\t\t\t<element type=\"Grants\" id=\"ID_INTERNAL_GRANTS_SPELLCASTING_BASE\" />",
  "\t\t\t<element type=\"Grants\" id=\"ID_INTERNAL_GRANTS_ARMOR_CLASS_BASE\" />",
  "\t\t\t<element type=\"Grants\" id=\"ID_INTERNAL_GRANTS_ARMOR_CLASS_DEXTERITY_MODIFIER\" />",
  "\t\t\t<element type=\"Grants\" id=\"ID_INTERNAL_GRANTS_HP_CONSTITUTION_MODIFIER\" />",
  "\t\t\t<element type=\"Race\" id=\"ID_RACE_GNOME\" />",
  "\t\t\t<element type=\"Size\" id=\"ID_SIZE_SMALL\" />",
  "\t\t\t<element type=\"Vision\" id=\"ID_VISION_DARKVISION\" />",
  "\t\t\t<element type=\"Racial Trait\" id=\"ID_RACIAL_TRAIT_GNOME_CUNNING\" />",
  "\t\t\t<element type=\"Language\" id=\"ID_LANGUAGE_COMMON\" />",
  "\t\t\t<element type=\"Language\" id=\"ID_LANGUAGE_GNOMISH\" />",
  "\t\t\t<element type=\"Racial Trait\" id=\"ID_RACIAL_TRAIT_GNOME_SUBRACE\" />",
  "\t\t\t<element type=\"Sub Race\" id=\"ID_SUB_RACE_ROCK_GNOME\" />",
  "\t\t\t<element type=\"Racial Trait\" id=\"ID_RACIAL_TRAIT_ARTIFICERS_LORE\" />",
  "\t\t\t<element type=\"Racial Trait\" id=\"ID_RACIAL_TRAIT_TINKER\" />",
  "\t\t\t<element type=\"Proficiency\" id=\"ID_PROFICIENCY_TOOL_PROFICIENCY_TINKERS_TOOLS\" />",
  "\t\t</sum>",
  "\t\t<magic />",
  "\t</build>",
  "\t<!-- restricted sources -->",
  "\t<sources>",
  "\t\t<restricted />",
  "\t</sources>",
  "</character>",
];

export const SAMPLE_CHARACTER = document(MINIMAL_LINES);

/**
 * A spellcasting character with equipment, adorners and restricted sources —
 * the sections the minimal sample leaves empty.
 */
const CASTER_LINES: readonly string[] = [
  "<?xml version=\"1.0\" encoding=\"utf-8\"?>",
  "<character version=\"1.0.3\" preview=\"false\">",
  "\t<!-- information -->",
  "\t<information>",
  "\t\t<group>",
  "\t\t</group>",
  "\t\t<generationOption>3</generationOption>",
  "\t</information>",
  "\t<!-- display data -->",
  "\t<display-properties favorite=\"false\">",
  "\t\t<name>Caster</name>",
  "\t\t<race>Kobold</race>",
  "\t\t<class>Paladin 5</class>",
  "\t\t<archetype>Oath of Devotion</archetype>",
  "\t\t<background>Acolyte</background>",
  "\t\t<level>5</level>",
  "\t</display-properties>",
  "\t<!-- build data -->",
  "\t<build>",
  "\t\t<input>",
  "\t\t\t<name>Caster</name>",
  "\t\t\t<gender>Female</gender>",
  "\t\t\t<player-name>Player Two</player-name>",
  "\t\t\t<experience>6500</experience>",
  "\t\t\t<backstory><![CDATA[You lived in seclusion, tending a shrine <of> stone & silence.]]></backstory>",
  "\t\t\t<attacks>",
  "\t\t\t\t<description><![CDATA[]]></description>",
  "\t\t\t\t<attack identifier=\"499e1747-79a0-45bb-a19a-ccf0c542fe29\" name=\"Shortsword\" range=\"5 ft\" attack=\"+6 vs AC\" damage=\"1d6+3 piercing\" displayed=\"true\" ability=\"Strength\">",
  "\t\t\t\t\t<description><![CDATA[Finesse, Light]]></description>",
  "\t\t\t\t</attack>",
  "\t\t\t\t<attack identifier=\"fb56bdbd-6a65-48cb-9bf4-b1dae2690f74\" name=\"Vicious Greataxe\" range=\"5 ft\" attack=\"+6 vs AC\" damage=\"1d12+3 slashing\" displayed=\"true\" ability=\"Strength\">",
  "\t\t\t\t\t<description><![CDATA[Heavy, Two-Handed]]></description>",
  "\t\t\t\t</attack>",
  "\t\t\t\t<attack identifier=\"19ba298e-8853-4960-a364-fcddcae0b84c\" name=\"Club\" range=\"5 ft\" attack=\"+6 vs AC\" damage=\"1d4+3 bludgeoning\" displayed=\"true\" ability=\"Strength\">",
  "\t\t\t\t\t<description><![CDATA[Light]]></description>",
  "\t\t\t\t</attack>",
  "\t\t\t</attacks>",
  "\t\t</input>",
  "\t\t<equipment>",
  "\t\t\t<item identifier=\"499e1747-79a0-45bb-a19a-ccf0c542fe29\" name=\"Shortsword\" id=\"ID_WOTC_PHB_WEAPON_SHORTSWORD\" amount=\"1\">",
  "\t\t\t\t<equipped location=\"Primary Hand\">true</equipped>",
  "\t\t\t</item>",
  "\t\t\t<item identifier=\"9b2d4e60-11ff-4a7c-8e35-0c1a2b3c4d5e\" name=\"Greataxe\" id=\"ID_WOTC_PHB_WEAPON_GREATAXE\" amount=\"1\" sidebar=\"true\">",
  "\t\t\t\t<items>",
  "\t\t\t\t\t<adorner name=\"Vicious Weapon\" id=\"ID_WOTC_DMG_MAGIC_ITEM_VICIOUS_WEAPON\" />",
  "\t\t\t\t</items>",
  "\t\t\t</item>",
  "\t\t\t<item identifier=\"b6a7e776-b667-40a4-99d1-5c2f80fb6849\" name=\"Potion of Healing\" id=\"ID_WOTC_DMG_MAGIC_ITEM_POTION_OF_HEALING\" amount=\"5\">",
  "\t\t\t\t<details card=\"true\">",
  "\t\t\t\t\t<name>",
  "\t\t\t\t\t</name>",
  "\t\t\t\t\t<notes>",
  "\t\t\t\t\t</notes>",
  "\t\t\t\t</details>",
  "\t\t\t</item>",
  "\t\t</equipment>",
  "\t\t<elements level-count=\"5\" registered-count=\"3\">",
  "\t\t\t<element type=\"Level\" name=\"1\" id=\"ID_LEVEL_1\">",
  "\t\t\t\t<element type=\"Race\" name=\"Race\" requiredLevel=\"1\" checksum=\"1597ef76\" registered=\"ID_RACE_KOBOLD\" />",
  "\t\t\t\t<element type=\"Class\" name=\"Class\" requiredLevel=\"1\" checksum=\"2a4b6c8d\" registered=\"ID_WOTC_PHB_CLASS_PALADIN\" />",
  "\t\t\t</element>",
  "\t\t\t<element type=\"Level\" name=\"2\" id=\"ID_LEVEL_2\" />",
  "\t\t\t<element type=\"Level\" name=\"3\" id=\"ID_LEVEL_3\" />",
  "\t\t\t<element type=\"Level\" name=\"4\" id=\"ID_LEVEL_4\" />",
  "\t\t\t<element type=\"Level\" name=\"5\" id=\"ID_LEVEL_5\" />",
  "\t\t</elements>",
  "\t\t<sum element-count=\"8\">",
  "\t\t\t<element type=\"Level\" id=\"ID_LEVEL_1\" />",
  "\t\t\t<element type=\"Level\" id=\"ID_LEVEL_2\" />",
  "\t\t\t<element type=\"Level\" id=\"ID_LEVEL_3\" />",
  "\t\t\t<element type=\"Level\" id=\"ID_LEVEL_4\" />",
  "\t\t\t<element type=\"Level\" id=\"ID_LEVEL_5\" />",
  "\t\t\t<element type=\"Grants\" id=\"ID_INTERNAL_GRANTS_CHARACTER_BASE\" />",
  "\t\t\t<element type=\"Class\" id=\"ID_WOTC_PHB_CLASS_PALADIN\" />",
  "\t\t\t<element type=\"Race\" id=\"ID_RACE_KOBOLD\" />",
  "\t\t</sum>",
  "\t\t<magic>",
  "\t\t\t<spellcasting name=\"Paladin\" ability=\"Charisma\" attack=\"6\" dc=\"14\" source=\"ID_WOTC_PHB_CLASS_FEATURE_PALADIN_SPELLCASTING\">",
  "\t\t\t\t<slots s1=\"4\" s2=\"2\" s3=\"0\" s4=\"0\" s5=\"0\" s6=\"0\" s7=\"0\" s8=\"0\" s9=\"0\" />",
  "\t\t\t\t<cantrips />",
  "\t\t\t\t<spells>",
  "\t\t\t\t\t<spell name=\"Bless\" level=\"1\" id=\"ID_PHB_SPELL_BLESS\" prepared=\"true\" />",
  "\t\t\t\t\t<spell name=\"Cure Wounds\" level=\"1\" id=\"ID_PHB_SPELL_CURE_WOUNDS\" prepared=\"true\" />",
  "\t\t\t\t\t<spell name=\"Divine Favor\" level=\"1\" id=\"ID_PHB_SPELL_DIVINE_FAVOR\" prepared=\"true\" />",
  "\t\t\t\t\t<spell name=\"Heroism\" level=\"1\" id=\"ID_PHB_SPELL_HEROISM\" prepared=\"true\" />",
  "\t\t\t\t\t<spell name=\"Protection from Evil and Good\" level=\"1\" id=\"ID_PHB_SPELL_PROTECTION_FROM_EVIL_AND_GOOD\" prepared=\"true\" always-prepared=\"true\" known=\"true\" />",
  "\t\t\t\t\t<spell name=\"Searing Smite\" level=\"1\" id=\"ID_PHB_SPELL_SEARING_SMITE\" />",
  "\t\t\t\t\t<spell name=\"Thunderous Smite\" level=\"1\" id=\"ID_PHB_SPELL_THUNDEROUS_SMITE\" />",
  "\t\t\t\t\t<spell name=\"Wrathful Smite\" level=\"1\" id=\"ID_PHB_SPELL_WRATHFUL_SMITE\" />",
  "\t\t\t\t\t<spell name=\"Compelled Duel\" level=\"1\" id=\"ID_PHB_SPELL_COMPELLED_DUEL\" />",
  "\t\t\t\t\t<spell name=\"Ceremony\" level=\"1\" id=\"ID_XGTE_SPELL_CEREMONY\" known=\"true\" />",
  "\t\t\t\t\t<spell name=\"Filler Spell 00\" level=\"2\" id=\"ID_TEST_SPELL_FILLER_00\" />",
  "\t\t\t\t\t<spell name=\"Filler Spell 01\" level=\"2\" id=\"ID_TEST_SPELL_FILLER_01\" />",
  "\t\t\t\t\t<spell name=\"Filler Spell 02\" level=\"2\" id=\"ID_TEST_SPELL_FILLER_02\" />",
  "\t\t\t\t\t<spell name=\"Filler Spell 03\" level=\"2\" id=\"ID_TEST_SPELL_FILLER_03\" />",
  "\t\t\t\t\t<spell name=\"Filler Spell 04\" level=\"2\" id=\"ID_TEST_SPELL_FILLER_04\" />",
  "\t\t\t\t\t<spell name=\"Filler Spell 05\" level=\"2\" id=\"ID_TEST_SPELL_FILLER_05\" />",
  "\t\t\t\t\t<spell name=\"Filler Spell 06\" level=\"2\" id=\"ID_TEST_SPELL_FILLER_06\" />",
  "\t\t\t\t\t<spell name=\"Filler Spell 07\" level=\"2\" id=\"ID_TEST_SPELL_FILLER_07\" />",
  "\t\t\t\t\t<spell name=\"Filler Spell 08\" level=\"2\" id=\"ID_TEST_SPELL_FILLER_08\" />",
  "\t\t\t\t\t<spell name=\"Filler Spell 09\" level=\"2\" id=\"ID_TEST_SPELL_FILLER_09\" />",
  "\t\t\t\t\t<spell name=\"Filler Spell 10\" level=\"2\" id=\"ID_TEST_SPELL_FILLER_10\" />",
  "\t\t\t\t\t<spell name=\"Filler Spell 11\" level=\"2\" id=\"ID_TEST_SPELL_FILLER_11\" />",
  "\t\t\t\t\t<spell name=\"Filler Spell 12\" level=\"2\" id=\"ID_TEST_SPELL_FILLER_12\" />",
  "\t\t\t\t\t<spell name=\"Filler Spell 13\" level=\"2\" id=\"ID_TEST_SPELL_FILLER_13\" />",
  "\t\t\t\t\t<spell name=\"Filler Spell 14\" level=\"2\" id=\"ID_TEST_SPELL_FILLER_14\" />",
  "\t\t\t\t\t<spell name=\"Filler Spell 15\" level=\"2\" id=\"ID_TEST_SPELL_FILLER_15\" />",
  "\t\t\t\t</spells>",
  "\t\t\t</spellcasting>",
  "\t\t</magic>",
  "\t</build>",
  "\t<!-- restricted sources -->",
  "\t<sources>",
  "\t\t<restricted>",
  "\t\t\t<source id=\"ID_KBP_DMBM_SOURCE_DEEP_MAGIC_BATTLE_MAGIC\">Deep Magic: Battle Magic</source>",
  "\t\t\t<source id=\"ID_KBP_DMBD_SOURCE_DEEP_MAGIC_BLOOD_AND_DOOM\">Deep Magic: Blood &amp; Doom</source>",
  "\t\t\t<source id=\"ID_WOTC_SOURCE_AL_TYRANNY_OF_DRAGONS\">Tyranny of Dragons</source>",
  "\t\t\t<source id=\"ID_TEST_SOURCE_00\">Test Source 00</source>",
  "\t\t\t<source id=\"ID_TEST_SOURCE_01\">Test Source 01</source>",
  "\t\t\t<source id=\"ID_TEST_SOURCE_02\">Test Source 02</source>",
  "\t\t\t<source id=\"ID_TEST_SOURCE_03\">Test Source 03</source>",
  "\t\t\t<source id=\"ID_TEST_SOURCE_04\">Test Source 04</source>",
  "\t\t\t<source id=\"ID_TEST_SOURCE_05\">Test Source 05</source>",
  "\t\t\t<source id=\"ID_TEST_SOURCE_06\">Test Source 06</source>",
  "\t\t\t<source id=\"ID_TEST_SOURCE_07\">Test Source 07</source>",
  "\t\t\t<source id=\"ID_TEST_SOURCE_08\">Test Source 08</source>",
  "\t\t\t<source id=\"ID_TEST_SOURCE_09\">Test Source 09</source>",
  "\t\t\t<source id=\"ID_TEST_SOURCE_10\">Test Source 10</source>",
  "\t\t\t<source id=\"ID_TEST_SOURCE_11\">Test Source 11</source>",
  "\t\t\t<source id=\"ID_TEST_SOURCE_12\">Test Source 12</source>",
  "\t\t\t<source id=\"ID_TEST_SOURCE_13\">Test Source 13</source>",
  "\t\t\t<source id=\"ID_TEST_SOURCE_14\">Test Source 14</source>",
  "\t\t\t<source id=\"ID_TEST_SOURCE_15\">Test Source 15</source>",
  "\t\t\t<source id=\"ID_TEST_SOURCE_16\">Test Source 16</source>",
  "\t\t\t<source id=\"ID_TEST_SOURCE_17\">Test Source 17</source>",
  "\t\t\t<source id=\"ID_TEST_SOURCE_18\">Test Source 18</source>",
  "\t\t\t<source id=\"ID_TEST_SOURCE_19\">Test Source 19</source>",
  "\t\t\t<source id=\"ID_TEST_SOURCE_20\">Test Source 20</source>",
  "\t\t\t<source id=\"ID_TEST_SOURCE_21\">Test Source 21</source>",
  "\t\t\t<source id=\"ID_TEST_SOURCE_22\">Test Source 22</source>",
  "\t\t\t<source id=\"ID_TEST_SOURCE_23\">Test Source 23</source>",
  "\t\t\t<source id=\"ID_TEST_SOURCE_24\">Test Source 24</source>",
  "\t\t\t<source id=\"ID_TEST_SOURCE_25\">Test Source 25</source>",
  "\t\t\t<source id=\"ID_TEST_SOURCE_26\">Test Source 26</source>",
  "\t\t\t<source id=\"ID_TEST_SOURCE_27\">Test Source 27</source>",
  "\t\t\t<source id=\"ID_TEST_SOURCE_28\">Test Source 28</source>",
  "\t\t\t<source id=\"ID_TEST_SOURCE_29\">Test Source 29</source>",
  "\t\t\t<element>ID_MHP_ARCHETYPE_FEATURE_THE_SHADOW_CABAL_WRAITH_FORM</element>",
  "\t\t</restricted>",
  "\t</sources>",
  "</character>",
];

export const SAMPLE_CASTER = document(CASTER_LINES);
