// Content profiles: which XML files the client bundles and, for the local
// test profiles, which corpus files stand in for the shipped baseline.
//
// The shipped baseline lives under apps/client/public/content and has three
// parts: the core rules baseline (`core/`), the System Reference Document 5.1
// subset (`srd-5.1/`) and the System Reference Document 5.2.1 subset
// (`srd-5.2.1/`). Both SRD subsets are generated by
// scripts/build-srd-content.mjs from the vendored corpus and the reviewed maps
// under third-party/srd-5.1 and third-party/srd-5.2; the few authored files in
// those directories are listed with them. The raw corpus tree itself is never
// bundled; it reaches the browser only through the upload flow or the explicit
// local test profiles below.

const PHB_CLASSES = [
  "barbarian",
  "bard",
  "cleric",
  "druid",
  "fighter",
  "monk",
  "paladin",
  "ranger",
  "rogue",
  "sorcerer",
  "warlock",
  "wizard",
];

const PHB_RACES = [
  "dragonborn",
  "dwarf",
  "elf",
  "gnome",
  "halfelf",
  "halfling",
  "halforc",
  "human",
  "tiefling",
];

const PHB_ITEM_GROUPS = ["armor", "gear", "instrument", "packs", "tools", "weapons"];
const DMG_MAGIC_GROUPS = ["armor", "poison", "potions", "rings", "rods", "staffs", "wands", "weapons", "wondrous"];
const LIVE_RELEASE_SOURCE_CATEGORIES = Object.freeze([
  "Core",
  "Internal",
  "Player’s Handbook",
  "Player’s Handbook (2024)",
  "System Reference Document",
]);

const CORE_2014_TEST_PATHS = new Set([
  "testdata/core/ALE.xml",
  "testdata/core/internal.xml",
  "testdata/core/players-handbook/source.xml",
  "testdata/core/players-handbook/backgrounds/background-acolyte.xml",
  "testdata/core/players-handbook/deities.xml",
  "testdata/core/players-handbook/languages.xml",
  "testdata/core/players-handbook/proficiencies.xml",
  "testdata/core/players-handbook/spells.xml",
  "testdata/core/players-handbook/archetypes/fighter-champion.xml",
  "testdata/core/players-handbook/archetypes/wizard-evocation.xml",
  ...PHB_CLASSES.map((name) => `testdata/core/players-handbook/classes/class-${name}.xml`),
  ...PHB_RACES.map((name) => `testdata/core/players-handbook/races/race-${name}.xml`),
  ...PHB_ITEM_GROUPS.map((name) => `testdata/core/players-handbook/items/items-${name}.xml`),
]);

// This is deliberately broader than the shipped profile. It retains the
// existing fixture corpus, including supplements and DMG item groups, without
// making those files part of the live browser bundle.
const REVIEWED_TEST_PATHS = new Set([
  ...CORE_2014_TEST_PATHS,
  "testdata/core/dungeon-masters-guide/source.xml",
  "testdata/core/monster-manual/source.xml",
  "testdata/supplements/extra-life/one-grung-above.xml",
  "testdata/supplements/xanathars-guide-to-everything/source.xml",
  "testdata/supplements/xanathars-guide-to-everything/spells.xml",
  "testdata/supplements/xanathars-guide-to-everything/archetypes/ranger-gloomstalker.xml",
  ...DMG_MAGIC_GROUPS.map((name) => `testdata/core/dungeon-masters-guide/items/items-${name}.xml`),
]);

// The core rules baseline: system elements every edition shares.
const CORE_PATHS = [
  "core/ability-score-increase.xml",
  "core/alignments.xml",
  "core/conditions.xml",
  "core/damage-types.xml",
  "core/experimental.xml",
  "core/internal/grants.xml",
  "core/internal/multiclassing.xml",
  "core/internal/options.xml",
  "core/internal/sources.xml",
  "core/internal/supports.xml",
  "core/internal/templates.xml",
  "core/languages.xml",
  "core/levels.xml",
  "core/proficiencies/armor.xml",
  "core/proficiencies/saving-throws.xml",
  "core/proficiencies/skill-expertise.xml",
  "core/proficiencies/skill-internal.xml",
  "core/proficiencies/skills.xml",
  "core/proficiencies/spellcasting-focus.xml",
  "core/proficiencies/tools-artisans.xml",
  "core/proficiencies/tools-gaming-sets.xml",
  "core/proficiencies/tools-kits.xml",
  "core/proficiencies/tools-misc.xml",
  "core/proficiencies/tools-musical-instruments.xml",
  "core/proficiencies/weapons.xml",
  "core/properties/armor.xml",
  "core/properties/firearms.xml",
  "core/properties/tools.xml",
  "core/properties/weapons.xml",
  "core/size.xml",
  "core/vision.xml",
];

// The System Reference Document 5.1 subset (2014 rules). Regenerate this list
// when the generator's output set changes (npm run content:build-srd).
const SRD_2014_PATHS = [
  "srd-5.1/archetypes/barbarian-berserker.xml",
  "srd-5.1/archetypes/bard-lore.xml",
  "srd-5.1/archetypes/cleric-life.xml",
  "srd-5.1/archetypes/druid-land.xml",
  "srd-5.1/archetypes/fighter-champion.xml",
  "srd-5.1/archetypes/monk-open-hand.xml",
  "srd-5.1/archetypes/paladin-devotion.xml",
  "srd-5.1/archetypes/ranger-hunter.xml",
  "srd-5.1/archetypes/rogue-thief.xml",
  "srd-5.1/archetypes/sorcerer-draconic.xml",
  "srd-5.1/archetypes/warlock-fiend.xml",
  "srd-5.1/archetypes/wizard-evocation.xml",
  "srd-5.1/backgrounds/background-acolyte.xml",
  "srd-5.1/classes/class-barbarian.xml",
  "srd-5.1/companions.xml",
  "srd-5.1/classes/class-bard.xml",
  "srd-5.1/classes/class-cleric.xml",
  "srd-5.1/classes/class-druid.xml",
  "srd-5.1/classes/class-fighter.xml",
  "srd-5.1/classes/class-monk.xml",
  "srd-5.1/classes/class-paladin.xml",
  "srd-5.1/classes/class-ranger.xml",
  "srd-5.1/classes/class-rogue.xml",
  "srd-5.1/classes/class-sorcerer.xml",
  "srd-5.1/classes/class-warlock.xml",
  "srd-5.1/classes/class-wizard.xml",
  "srd-5.1/deities.xml",
  "srd-5.1/eldritch-invocations.xml",
  "srd-5.1/feats.xml",
  "srd-5.1/internal.xml",
  "srd-5.1/items/items-armor.xml",
  "srd-5.1/items/items-gear.xml",
  "srd-5.1/items/items-instrument.xml",
  "srd-5.1/items/items-mounts.xml",
  "srd-5.1/items/items-packs.xml",
  "srd-5.1/items/items-tools.xml",
  "srd-5.1/items/items-weapons.xml",
  "srd-5.1/items/magic/items-armor.xml",
  "srd-5.1/items/magic/items-poison.xml",
  "srd-5.1/items/magic/items-potions.xml",
  "srd-5.1/items/magic/items-rings.xml",
  "srd-5.1/items/magic/items-rods.xml",
  "srd-5.1/items/magic/items-staffs.xml",
  "srd-5.1/items/magic/items-wands.xml",
  "srd-5.1/items/magic/items-weapons.xml",
  "srd-5.1/items/magic/items-wondrous.xml",
  "srd-5.1/races/race-dragonborn.xml",
  "srd-5.1/races/race-dwarf.xml",
  "srd-5.1/races/race-elf.xml",
  "srd-5.1/races/race-gnome.xml",
  "srd-5.1/races/race-halfelf.xml",
  "srd-5.1/races/race-halfling.xml",
  "srd-5.1/races/race-halforc.xml",
  "srd-5.1/races/race-human.xml",
  "srd-5.1/races/race-tiefling.xml",
  "srd-5.1/ranger-favored-terrains.xml",
  "srd-5.1/spells.xml",
];

// The System Reference Document 5.2.1 subset (2024 rules), plus three authored
// files: the Source element, the skill tags for the shipped skill elements, and
// the "Skill Expertise" proficiency elements the 2024 classes and feats select
// from. Regenerate this list when the generator's output set changes.
const SRD_2024_PATHS = [
  "srd-5.2.1/archetypes/barbarian-berserker.xml",
  "srd-5.2.1/archetypes/bard-lore.xml",
  "srd-5.2.1/archetypes/cleric-life.xml",
  "srd-5.2.1/archetypes/druid-land.xml",
  "srd-5.2.1/archetypes/fighter-champion.xml",
  "srd-5.2.1/archetypes/monk-open-hand.xml",
  "srd-5.2.1/archetypes/paladin-devotion.xml",
  "srd-5.2.1/archetypes/ranger-hunter.xml",
  "srd-5.2.1/archetypes/rogue-thief.xml",
  "srd-5.2.1/archetypes/sorcerer-draconic.xml",
  "srd-5.2.1/archetypes/warlock-fiend.xml",
  "srd-5.2.1/archetypes/wizard-evoker.xml",
  "srd-5.2.1/backgrounds/background-acolyte.xml",
  "srd-5.2.1/backgrounds/background-criminal.xml",
  "srd-5.2.1/backgrounds/background-sage.xml",
  "srd-5.2.1/backgrounds/background-soldier.xml",
  "srd-5.2.1/classes/class-barbarian.xml",
  "srd-5.2.1/classes/class-bard.xml",
  "srd-5.2.1/classes/class-cleric.xml",
  "srd-5.2.1/classes/class-druid.xml",
  "srd-5.2.1/classes/class-fighter.xml",
  "srd-5.2.1/classes/class-monk.xml",
  "srd-5.2.1/classes/class-paladin.xml",
  "srd-5.2.1/classes/class-ranger.xml",
  "srd-5.2.1/classes/class-rogue.xml",
  "srd-5.2.1/classes/class-sorcerer.xml",
  "srd-5.2.1/classes/class-warlock.xml",
  "srd-5.2.1/classes/class-wizard.xml",
  "srd-5.2.1/classes/eldritch-invocations.xml",
  "srd-5.2.1/companions.xml",
  "srd-5.2.1/feats/feats-epic-boons.xml",
  "srd-5.2.1/feats/feats-fighting-styles.xml",
  "srd-5.2.1/feats/feats-general.xml",
  "srd-5.2.1/feats/feats-origin.xml",
  "srd-5.2.1/internal.xml",
  "srd-5.2.1/items/items-armor.xml",
  "srd-5.2.1/items/items-gear.xml",
  "srd-5.2.1/items/items-mounts-vehicles.xml",
  "srd-5.2.1/items/items-packs.xml",
  "srd-5.2.1/items/items-tools.xml",
  "srd-5.2.1/items/items-weapons.xml",
  "srd-5.2.1/misc/languages.xml",
  "srd-5.2.1/misc/proficiencies.xml",
  "srd-5.2.1/misc/weapon-mastery-properties.xml",
  "srd-5.2.1/races/race-dragonborn.xml",
  "srd-5.2.1/races/race-dwarf.xml",
  "srd-5.2.1/races/race-elf.xml",
  "srd-5.2.1/races/race-gnome.xml",
  "srd-5.2.1/races/race-goliath.xml",
  "srd-5.2.1/races/race-halfling.xml",
  "srd-5.2.1/races/race-human.xml",
  "srd-5.2.1/races/race-orc.xml",
  "srd-5.2.1/races/race-tiefling.xml",
  "srd-5.2.1/rules.xml",
  "srd-5.2.1/skill-expertise.xml",
  "srd-5.2.1/skill-supports.xml",
  "srd-5.2.1/source.xml",
  "srd-5.2.1/spells.xml",
];

const PUBLIC_BASE_PATHS = new Set([...CORE_PATHS, ...SRD_2014_PATHS, ...SRD_2024_PATHS]);

export const CONTENT_PROFILES = Object.freeze({
  "public-base": Object.freeze({
    name: "public-base",
    isBundled: true,
    sourceCategories: LIVE_RELEASE_SOURCE_CATEGORIES,
    includes(relativePath) {
      return (
        relativePath === "system/system-proxies.xml" ||
        relativePath === "system/system-unarmed-riders.xml" ||
        PUBLIC_BASE_PATHS.has(relativePath)
      );
    },
  }),
  "reviewed-test": Object.freeze({
    name: "reviewed-test",
    isBundled: false,
    sourceCategories: Object.freeze([
      ...LIVE_RELEASE_SOURCE_CATEGORIES,
      "Dungeon Master’s Guide",
      "Monster Manual",
      "One Grung Above",
      "Xanathar’s Guide to Everything",
    ]),
    includes(relativePath) {
      return (
        (relativePath === "system/system-elements.xml" ||
          relativePath === "system/system-proxies.xml" ||
          relativePath === "system/system-unarmed-riders.xml") ||
        REVIEWED_TEST_PATHS.has(relativePath)
      );
    },
  }),
  full: Object.freeze({
    name: "full",
    isBundled: false,
    sourceCategories: Object.freeze([]),
    includes() {
      return true;
    },
  }),
});

export function resolveContentProfile(profile = "public-base") {
  const resolved = CONTENT_PROFILES[String(profile).trim()] ?? CONTENT_PROFILES["public-base"];
  return resolved;
}

export { CORE_PATHS, CORE_2014_TEST_PATHS, LIVE_RELEASE_SOURCE_CATEGORIES, PUBLIC_BASE_PATHS, REVIEWED_TEST_PATHS, SRD_2014_PATHS, SRD_2024_PATHS };
